[package]
name = "witx-codegen"
version = "0.2.0"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
convert_case = "0.4"
witx = { git = "https://github.com/alexcrichton/WASI.git", branch = "abi-next" }
