name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Run functional tests
        run: |
          cargo run -- --output-type=overview tests/*.witx > /dev/null
          cargo run -- --output-type=markdown tests/*.witx > /dev/null
          cargo run -- --output-type=assemblyscript tests/*.witx > /dev/null
          cargo run -- --output-type=zig tests/*.witx > /dev/null
          cargo run -- --output-type=rust tests/*.witx > /dev/null
      - name: Check that crates version works
        run: cargo install witx-docgen --debug
